#!/bin/bash
FILE=restaurante

# Ejecuto exec de las shared
./../shared/exec

if [[ ! -d bin ]]; then
    mkdir bin
fi
make bin/$FILE

if [[ ! -e cfg/$FILE.log ]]; then
    mkdir cfg
    touch cfg/$FILE.log
fi