#!/bin/bash
FILE=comanda

# Ejecuto exec de las shared
./../shared/exec

if [[ ! -d bin ]]; then
    mkdir bin
fi
make bin/$FILE

if [[ ! -e cfg/$FILE.log ]]; then
    mkdir cfg
    touch cfg/$FILE.log
fi

if test -f "./bin/$FILE"; then
    valgrind --tool=memcheck --leak-check=yes --show-possibly-lost=no --show-reachable=no --num-callers=20 ./bin/$FILE
fi